var jhath = {
  login: "jhath16",
  id: 2738288,
  avatar_url: "https://avatars.githubusercontent.com/u/2738288?v=2",
  gravatar_id: "5c265b09c28ab81d306bd6baeb2bee39",
  url: "https://api.github.com/users/jhath16",
  html_url: "https://github.com/jhath16",
  followers_url: "https://api.github.com/users/jhath16/followers",
  following_url: "https://api.github.com/users/jhath16/following{/other_user}",
  gists_url: "https://api.github.com/users/jhath16/gists{/gist_id}",
  starred_url: "https://api.github.com/users/jhath16/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/jhath16/subscriptions",
  organizations_url: "https://api.github.com/users/jhath16/orgs",
  repos_url: "https://api.github.com/users/jhath16/repos",
  events_url: "https://api.github.com/users/jhath16/events{/privacy}",
  received_events_url: "https://api.github.com/users/jhath16/received_events",
  type: "User",
  site_admin: false,
  name: "Justin Hathaway",
  company: "",
  blog: "",
  location: "",
  email: "hathaway.justin@gmail.com",
  hireable: false,
  bio: null,
  public_repos: 10,
  public_gists: 0,
  followers: 2,
  following: 2,
  created_at: "2012-11-06T21:19:48Z",
  updated_at: "2014-09-10T21:47:46Z"
};
